name: mightyweb
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BASE
  nb_utils: ^4.6.20
  google_fonts: ^3.0.1

  #UI
  cached_network_image: ^3.2.2
  flutter_spinkit: ^5.1.0
  package_info_plus: ^1.4.3+1
  flutter_speed_dial: ^6.0.0

  #STATE MANAGEMENT
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1

  #STORAGE & PERMISSION
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  provider: ^6.0.3

  #CONNECTIVITY
  http: ^0.13.5
  share_plus: ^4.1.0
  url_launcher: ^6.1.5
  store_redirect: ^2.0.1

  #Firebase
  firebase_in_app_messaging: ^0.6.0+24
  firebase_messaging: ^13.0.1
  firebase_core: ^1.22.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.4.1

  # ADS
  google_mobile_ads: ^2.0.1
  facebook_audience_network: ^1.0.1

  # WEB TOOLS
  flutter_inappwebview: ^5.4.3+7

  qr_code_scanner: ^1.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
